/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CreatePerformancePayload = IDL.Record({
  'month' : IDL.Nat,
  'overallScore' : IDL.Float64,
  'internId' : IDL.Text,
  'year' : IDL.Nat,
  'initiativeScore' : IDL.Float64,
  'attendanceScore' : IDL.Float64,
  'taskScore' : IDL.Float64,
  'communicationScore' : IDL.Float64,
  'adminNotes' : IDL.Text,
});
export const Performance = IDL.Record({
  'id' : IDL.Text,
  'month' : IDL.Nat,
  'overallScore' : IDL.Float64,
  'internId' : IDL.Text,
  'createdAt' : IDL.Int,
  'year' : IDL.Nat,
  'initiativeScore' : IDL.Float64,
  'attendanceScore' : IDL.Float64,
  'taskScore' : IDL.Float64,
  'communicationScore' : IDL.Float64,
  'adminNotes' : IDL.Text,
});
export const Status = IDL.Variant({
  'OnHold' : IDL.Null,
  'Active' : IDL.Null,
  'Completed' : IDL.Null,
});
export const ExperienceLevel = IDL.Variant({
  'Mid' : IDL.Null,
  'Junior' : IDL.Null,
  'Senior' : IDL.Null,
});
export const Space = IDL.Variant({
  'Org' : IDL.Null,
  'Learning' : IDL.Null,
  'Marketing' : IDL.Null,
});
export const CreateInternPayload = IDL.Record({
  'status' : Status,
  'experienceLevel' : ExperienceLevel,
  'profilePicCid' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'joiningDate' : IDL.Int,
  'email' : IDL.Text,
  'space' : Space,
  'phone' : IDL.Text,
  'department' : IDL.Text,
  'adminNotes' : IDL.Text,
});
export const Intern = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'experienceLevel' : ExperienceLevel,
  'profilePicCid' : IDL.Opt(IDL.Text),
  'offerLetterSentAt' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'joiningDate' : IDL.Int,
  'certificateOpened' : IDL.Bool,
  'completionLetterOpened' : IDL.Bool,
  'email' : IDL.Text,
  'lastWhatsAppedAt' : IDL.Opt(IDL.Int),
  'certificateOpenedAt' : IDL.Opt(IDL.Int),
  'space' : Space,
  'updatedAt' : IDL.Int,
  'offerLetterSent' : IDL.Bool,
  'certificateSentAt' : IDL.Opt(IDL.Int),
  'completionLetterSentAt' : IDL.Opt(IDL.Int),
  'completionLetterSent' : IDL.Bool,
  'offerLetterOpenedAt' : IDL.Opt(IDL.Int),
  'completionLetterOpenedAt' : IDL.Opt(IDL.Int),
  'phone' : IDL.Text,
  'department' : IDL.Text,
  'lastContactedAt' : IDL.Opt(IDL.Int),
  'adminNotes' : IDL.Text,
  'offerLetterOpened' : IDL.Bool,
  'certificateSent' : IDL.Bool,
});
export const Activity = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'internId' : IDL.Text,
  'performedBy' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'marketingCount' : IDL.Nat,
  'documentsSentThisMonth' : IDL.Nat,
  'orgCount' : IDL.Nat,
  'totalInterns' : IDL.Nat,
  'activeInterns' : IDL.Nat,
  'learningCount' : IDL.Nat,
  'avgPerformance' : IDL.Float64,
});
export const ListInternsFilter = IDL.Record({
  'status' : IDL.Opt(Status),
  'space' : IDL.Opt(Space),
});
export const UpdateInternPayload = IDL.Record({
  'status' : Status,
  'experienceLevel' : ExperienceLevel,
  'profilePicCid' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'joiningDate' : IDL.Int,
  'email' : IDL.Text,
  'space' : Space,
  'phone' : IDL.Text,
  'department' : IDL.Text,
  'adminNotes' : IDL.Text,
});
export const UpdatePerformancePayload = IDL.Record({
  'month' : IDL.Nat,
  'overallScore' : IDL.Float64,
  'year' : IDL.Nat,
  'initiativeScore' : IDL.Float64,
  'attendanceScore' : IDL.Float64,
  'taskScore' : IDL.Float64,
  'communicationScore' : IDL.Float64,
  'adminNotes' : IDL.Text,
});

export const idlService = IDL.Service({
  'addPerformance' : IDL.Func(
      [IDL.Text, CreatePerformancePayload],
      [IDL.Variant({ 'ok' : Performance, 'err' : IDL.Text })],
      [],
    ),
  'createIntern' : IDL.Func(
      [IDL.Text, CreateInternPayload],
      [IDL.Variant({ 'ok' : Intern, 'err' : IDL.Text })],
      [],
    ),
  'deleteIntern' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deletePerformance' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'getActivities' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Activity)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getIntern' : IDL.Func([IDL.Text], [IDL.Opt(Intern)], ['query']),
  'initSampleData' : IDL.Func([], [IDL.Nat], []),
  'listInterns' : IDL.Func([ListInternsFilter], [IDL.Vec(Intern)], ['query']),
  'listPerformances' : IDL.Func([IDL.Text], [IDL.Vec(Performance)], ['query']),
  'logWhatsApp' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'displayName' : IDL.Text,
            'sessionToken' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'logout' : IDL.Func([IDL.Text], [], []),
  'seedSampleData' : IDL.Func([], [], []),
  'updateDocumentState' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'updateIntern' : IDL.Func(
      [IDL.Text, IDL.Text, UpdateInternPayload],
      [IDL.Variant({ 'ok' : Intern, 'err' : IDL.Text })],
      [],
    ),
  'updatePerformance' : IDL.Func(
      [IDL.Text, IDL.Text, UpdatePerformancePayload],
      [IDL.Variant({ 'ok' : Performance, 'err' : IDL.Text })],
      [],
    ),
  'validateSession' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'username' : IDL.Text,
            'displayName' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CreatePerformancePayload = IDL.Record({
    'month' : IDL.Nat,
    'overallScore' : IDL.Float64,
    'internId' : IDL.Text,
    'year' : IDL.Nat,
    'initiativeScore' : IDL.Float64,
    'attendanceScore' : IDL.Float64,
    'taskScore' : IDL.Float64,
    'communicationScore' : IDL.Float64,
    'adminNotes' : IDL.Text,
  });
  const Performance = IDL.Record({
    'id' : IDL.Text,
    'month' : IDL.Nat,
    'overallScore' : IDL.Float64,
    'internId' : IDL.Text,
    'createdAt' : IDL.Int,
    'year' : IDL.Nat,
    'initiativeScore' : IDL.Float64,
    'attendanceScore' : IDL.Float64,
    'taskScore' : IDL.Float64,
    'communicationScore' : IDL.Float64,
    'adminNotes' : IDL.Text,
  });
  const Status = IDL.Variant({
    'OnHold' : IDL.Null,
    'Active' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const ExperienceLevel = IDL.Variant({
    'Mid' : IDL.Null,
    'Junior' : IDL.Null,
    'Senior' : IDL.Null,
  });
  const Space = IDL.Variant({
    'Org' : IDL.Null,
    'Learning' : IDL.Null,
    'Marketing' : IDL.Null,
  });
  const CreateInternPayload = IDL.Record({
    'status' : Status,
    'experienceLevel' : ExperienceLevel,
    'profilePicCid' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'joiningDate' : IDL.Int,
    'email' : IDL.Text,
    'space' : Space,
    'phone' : IDL.Text,
    'department' : IDL.Text,
    'adminNotes' : IDL.Text,
  });
  const Intern = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'experienceLevel' : ExperienceLevel,
    'profilePicCid' : IDL.Opt(IDL.Text),
    'offerLetterSentAt' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'joiningDate' : IDL.Int,
    'certificateOpened' : IDL.Bool,
    'completionLetterOpened' : IDL.Bool,
    'email' : IDL.Text,
    'lastWhatsAppedAt' : IDL.Opt(IDL.Int),
    'certificateOpenedAt' : IDL.Opt(IDL.Int),
    'space' : Space,
    'updatedAt' : IDL.Int,
    'offerLetterSent' : IDL.Bool,
    'certificateSentAt' : IDL.Opt(IDL.Int),
    'completionLetterSentAt' : IDL.Opt(IDL.Int),
    'completionLetterSent' : IDL.Bool,
    'offerLetterOpenedAt' : IDL.Opt(IDL.Int),
    'completionLetterOpenedAt' : IDL.Opt(IDL.Int),
    'phone' : IDL.Text,
    'department' : IDL.Text,
    'lastContactedAt' : IDL.Opt(IDL.Int),
    'adminNotes' : IDL.Text,
    'offerLetterOpened' : IDL.Bool,
    'certificateSent' : IDL.Bool,
  });
  const Activity = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'internId' : IDL.Text,
    'performedBy' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'marketingCount' : IDL.Nat,
    'documentsSentThisMonth' : IDL.Nat,
    'orgCount' : IDL.Nat,
    'totalInterns' : IDL.Nat,
    'activeInterns' : IDL.Nat,
    'learningCount' : IDL.Nat,
    'avgPerformance' : IDL.Float64,
  });
  const ListInternsFilter = IDL.Record({
    'status' : IDL.Opt(Status),
    'space' : IDL.Opt(Space),
  });
  const UpdateInternPayload = IDL.Record({
    'status' : Status,
    'experienceLevel' : ExperienceLevel,
    'profilePicCid' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'joiningDate' : IDL.Int,
    'email' : IDL.Text,
    'space' : Space,
    'phone' : IDL.Text,
    'department' : IDL.Text,
    'adminNotes' : IDL.Text,
  });
  const UpdatePerformancePayload = IDL.Record({
    'month' : IDL.Nat,
    'overallScore' : IDL.Float64,
    'year' : IDL.Nat,
    'initiativeScore' : IDL.Float64,
    'attendanceScore' : IDL.Float64,
    'taskScore' : IDL.Float64,
    'communicationScore' : IDL.Float64,
    'adminNotes' : IDL.Text,
  });
  
  return IDL.Service({
    'addPerformance' : IDL.Func(
        [IDL.Text, CreatePerformancePayload],
        [IDL.Variant({ 'ok' : Performance, 'err' : IDL.Text })],
        [],
      ),
    'createIntern' : IDL.Func(
        [IDL.Text, CreateInternPayload],
        [IDL.Variant({ 'ok' : Intern, 'err' : IDL.Text })],
        [],
      ),
    'deleteIntern' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deletePerformance' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'getActivities' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getIntern' : IDL.Func([IDL.Text], [IDL.Opt(Intern)], ['query']),
    'initSampleData' : IDL.Func([], [IDL.Nat], []),
    'listInterns' : IDL.Func([ListInternsFilter], [IDL.Vec(Intern)], ['query']),
    'listPerformances' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Performance)],
        ['query'],
      ),
    'logWhatsApp' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'displayName' : IDL.Text,
              'sessionToken' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'logout' : IDL.Func([IDL.Text], [], []),
    'seedSampleData' : IDL.Func([], [], []),
    'updateDocumentState' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'updateIntern' : IDL.Func(
        [IDL.Text, IDL.Text, UpdateInternPayload],
        [IDL.Variant({ 'ok' : Intern, 'err' : IDL.Text })],
        [],
      ),
    'updatePerformance' : IDL.Func(
        [IDL.Text, IDL.Text, UpdatePerformancePayload],
        [IDL.Variant({ 'ok' : Performance, 'err' : IDL.Text })],
        [],
      ),
    'validateSession' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'username' : IDL.Text,
              'displayName' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };