/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : string,
  'action' : string,
  'internId' : string,
  'performedBy' : string,
  'timestamp' : bigint,
  'details' : string,
}
export type ActivityType = { 'whatsappMessage' : null } |
  { 'callScheduled' : null } |
  { 'statusChange' : null } |
  { 'proposalUploaded' : null } |
  { 'noteAdded' : null } |
  { 'documentShared' : null } |
  { 'commentAdded' : null } |
  { 'invoiceGenerated' : null } |
  { 'quickMeeting' : null } |
  { 'quickEmail' : null } |
  { 'quickCall' : null };
export interface AnalyticsData {
  'weightedForecast' : bigint,
  'conversionRates' : Array<[string, bigint]>,
  'totalPipeline' : bigint,
  'avgDealCycleDays' : bigint,
  'winRate' : bigint,
  'wonLostBreakdown' : Array<[string, bigint]>,
}
export interface Announcement {
  'id' : string,
  'title' : string,
  'content' : string,
  'expiresAt' : [] | [bigint],
  'createdAt' : bigint,
  'createdBy' : string,
  'isActive' : boolean,
  'targetSpaces' : [] | [Array<string>],
}
export interface ApprovalRequest {
  'id' : string,
  'status' : ApprovalStatus,
  'resourceId' : string,
  'approverId' : [] | [string],
  'createdAt' : bigint,
  'actionType' : string,
  'requestPayload' : string,
  'resourceType' : string,
  'notes' : [] | [string],
  'requesterRole' : string,
  'requesterId' : string,
  'resolvedAt' : [] | [bigint],
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AuditEvent {
  'id' : string,
  'beforeState' : [] | [string],
  'action' : string,
  'actorRole' : string,
  'resourceId' : string,
  'actorId' : string,
  'resourceType' : string,
  'timestamp' : bigint,
  'afterState' : [] | [string],
  'ipAddress' : [] | [string],
}
export interface Channel {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'spaceId' : string,
  'memberIds' : Array<string>,
}
export interface ChannelMessage {
  'id' : string,
  'content' : string,
  'channelId' : string,
  'createdAt' : bigint,
  'senderName' : string,
  'mentions' : Array<string>,
  'senderId' : string,
}
export interface Client {
  'id' : string,
  'dealProbability' : bigint,
  'isStale' : [] | [boolean],
  'contacts' : Array<ContactPerson>,
  'source' : string,
  'serviceInterested' : string,
  'pipelineValue' : [] | [number],
  'gstNumber' : [] | [string],
  'stageEnteredAt' : [] | [bigint],
  'lastActivity' : [] | [bigint],
  'designation' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'tags' : Array<string>,
  'leadScore' : bigint,
  'lastActivityDate' : [] | [bigint],
  'statusHistory' : Array<StatusHistoryEntry>,
  'email' : string,
  'website' : string,
  'proposalExpiry' : [] | [bigint],
  'slaBreachedAt' : [] | [bigint],
  'proposalVersion' : bigint,
  'whatsappNumber' : string,
  'customFields' : Array<[string, string]>,
  'updatedAt' : bigint,
  'closedAt' : [] | [bigint],
  'wonLostReason' : [] | [string],
  'nextMeetingDate' : [] | [bigint],
  'companyName' : string,
  'leadSource' : string,
  'priorityLevel' : PriorityLevel,
  'dealValue' : number,
  'companySize' : string,
  'proposalStatus' : [] | [string],
  'healthScore' : bigint,
  'phone' : string,
  'engagementScore' : bigint,
  'industryType' : string,
  'contactPersonName' : string,
  'slaStatus' : [] | [SlaStatus],
  'assignedTeamMember' : string,
  'location' : string,
  'activityCount' : bigint,
  'currentStatus' : ClientStatus,
  'closedReason' : [] | [string],
  'followUpDate' : [] | [bigint],
}
export interface ClientActivity {
  'id' : string,
  'clientId' : string,
  'activityType' : ActivityType,
  'metadata' : [] | [string],
  'description' : string,
  'adminName' : string,
  'timestamp' : bigint,
}
export interface ClientAnalytics {
  'rejectedLeads' : bigint,
  'totalClients' : bigint,
  'monthlyData' : Array<MonthlyAnalyticsEntry>,
  'activeLeads' : bigint,
  'approvedDeals' : bigint,
  'revenuePipeline' : number,
}
export interface ClientComment {
  'id' : string,
  'clientId' : string,
  'content' : string,
  'authorName' : string,
  'timestamp' : bigint,
  'parentId' : [] | [string],
  'isPinned' : boolean,
}
export type ClientStatus = { 'discoveryCallDone' : null } |
  { 'closedWon' : null } |
  { 'leadCaptured' : null } |
  { 'proposalSent' : null } |
  { 'contacted' : null } |
  { 'negotiation' : null } |
  { 'onHold' : null } |
  { 'closedLost' : null };
export interface CompositePerformanceScore {
  'learningScore' : bigint,
  'improvementSuggestions' : Array<string>,
  'overallScore' : bigint,
  'internId' : string,
  'productivityScore' : bigint,
  'computedAt' : bigint,
  'attendanceScore' : bigint,
  'communicationScore' : bigint,
}
export interface ContactPerson {
  'id' : string,
  'name' : string,
  'role' : string,
  'email' : string,
  'isPrimary' : boolean,
  'addedAt' : bigint,
  'phone' : string,
}
export interface CreateClientRequest {
  'source' : string,
  'serviceInterested' : string,
  'gstNumber' : [] | [string],
  'designation' : string,
  'tags' : Array<string>,
  'email' : string,
  'website' : string,
  'whatsappNumber' : string,
  'nextMeetingDate' : [] | [bigint],
  'companyName' : string,
  'leadSource' : string,
  'priorityLevel' : PriorityLevel,
  'dealValue' : number,
  'companySize' : string,
  'phone' : string,
  'industryType' : string,
  'contactPersonName' : string,
  'assignedTeamMember' : string,
  'location' : string,
  'followUpDate' : [] | [bigint],
}
export interface CreateDailyNotePayload {
  'workedOn' : string,
  'blockers' : string,
  'internId' : string,
  'date' : string,
  'progress' : string,
  'learningUpdates' : string,
}
export interface CreateInternPayload {
  'status' : Status,
  'experienceLevel' : ExperienceLevel,
  'profilePicCid' : [] | [string],
  'name' : string,
  'joiningDate' : bigint,
  'email' : string,
  'space' : Space,
  'phone' : string,
  'department' : string,
  'adminNotes' : string,
}
export interface CreateMeetingPayload {
  'title' : string,
  'joinLink' : [] | [string],
  'meetingType' : string,
  'durationMinutes' : bigint,
  'participantIds' : Array<string>,
  'scheduledAt' : bigint,
}
export interface CreatePerformancePayload {
  'month' : bigint,
  'overallScore' : number,
  'internId' : string,
  'year' : bigint,
  'initiativeScore' : number,
  'attendanceScore' : number,
  'taskScore' : number,
  'communicationScore' : number,
  'adminNotes' : string,
}
export interface CreateSubmissionPayload {
  'title' : string,
  'githubLink' : [] | [string],
  'internId' : string,
  'description' : string,
  'fileUrls' : Array<string>,
  'driveLink' : [] | [string],
  'taskId' : [] | [string],
}
export interface CreateTaskPayload {
  'title' : string,
  'tags' : Array<string>,
  'description' : string,
  'deadline' : [] | [bigint],
  'assignedInternId' : string,
  'teamSpace' : string,
  'priority' : string,
}
export interface DailyNote {
  'id' : string,
  'workedOn' : string,
  'adminComments' : Array<NoteComment>,
  'blockers' : string,
  'internId' : string,
  'date' : string,
  'createdAt' : bigint,
  'progress' : string,
  'learningUpdates' : string,
}
export interface DashboardSnapshot {
  'totalRevenueYTD' : number,
  'closedDealsThisMonth' : bigint,
  'slaBreaachRatePerStage' : Array<[string, number]>,
  'pipelineVelocity' : Array<[string, number]>,
  'revenueForecast' : number,
  'activeDealsCount' : bigint,
  'updatedAt' : bigint,
  'winRateByRep' : Array<[string, number]>,
  'followUpComplianceRate' : Array<[string, number]>,
}
export interface DashboardStats {
  'marketingCount' : bigint,
  'documentsSentThisMonth' : bigint,
  'orgCount' : bigint,
  'totalInterns' : bigint,
  'activeInterns' : bigint,
  'learningCount' : bigint,
  'avgPerformance' : number,
}
export interface DirectMessage {
  'id' : string,
  'content' : string,
  'createdAt' : bigint,
  'isRead' : boolean,
  'toUserId' : string,
  'fromUserId' : string,
}
export interface DocumentRecord {
  'internId' : string,
  'fileName' : string,
  'isArchived' : boolean,
  'currentVersion' : string,
  'category' : string,
  'versions' : Array<DocumentVersion>,
  'docType' : string,
  'docId' : string,
}
export interface DocumentVersion {
  'id' : string,
  'generatedAt' : bigint,
  'generatedBy' : string,
  'approvalStatus' : string,
  'version' : string,
  'notes' : string,
  'docType' : string,
}
export type ExperienceLevel = { 'Mid' : null } |
  { 'Junior' : null } |
  { 'Senior' : null };
export interface Intern {
  'id' : string,
  'dob' : [] | [string],
  'status' : Status,
  'experienceLevel' : ExperienceLevel,
  'profilePicCid' : [] | [string],
  'performanceTier' : [] | [string],
  'actualEndDate' : [] | [string],
  'offerLetterSentAt' : [] | [bigint],
  'domain' : [] | [string],
  'stipendAmount' : [] | [number],
  'mentorAssigned' : [] | [string],
  'name' : string,
  'createdAt' : bigint,
  'emergencyContact' : [] | [string],
  'joiningDate' : bigint,
  'certificateOpened' : boolean,
  'completionLetterOpened' : boolean,
  'isActive' : boolean,
  'email' : string,
  'lastWhatsAppedAt' : [] | [bigint],
  'certificateOpenedAt' : [] | [bigint],
  'space' : Space,
  'updatedAt' : bigint,
  'pipelineStage' : InternPipelineStage,
  'offerLetterSent' : boolean,
  'gender' : [] | [string],
  'degreeYear' : [] | [string],
  'certificateSentAt' : [] | [bigint],
  'completionLetterSentAt' : [] | [bigint],
  'completionLetterSent' : boolean,
  'offerLetterOpenedAt' : [] | [bigint],
  'completionLetterOpenedAt' : [] | [bigint],
  'phone' : string,
  'department' : string,
  'lastContactedAt' : [] | [bigint],
  'adminNotes' : string,
  'offerLetterOpened' : boolean,
  'certificateSent' : boolean,
  'college' : [] | [string],
  'expectedEndDate' : [] | [string],
  'ppoCandidate' : boolean,
  'startDate' : [] | [string],
  'internshipType' : [] | [string],
}
export type InternPipelineStage = { 'offerSent' : null } |
  { 'active' : null } |
  { 'offerRejected' : null } |
  { 'offerAccepted' : null } |
  { 'alumni' : null } |
  { 'applied' : null } |
  { 'completed' : null } |
  { 'performanceReview' : null } |
  { 'interviewDone' : null } |
  { 'interviewScheduled' : null } |
  { 'onboarding' : null } |
  { 'decisionPending' : null } |
  { 'screened' : null };
export interface InternPipelineStageHistory {
  'changedAt' : bigint,
  'changedBy' : string,
  'stage' : InternPipelineStage,
  'notes' : string,
}
export interface Invoice {
  'id' : string,
  'tax' : number,
  'status' : InvoicePaymentStatus,
  'lineItems' : Array<InvoiceLineItem>,
  'total' : number,
  'clientId' : string,
  'paymentStatus' : PaymentStatus,
  'createdAt' : bigint,
  'createdBy' : string,
  'dueDate' : [] | [bigint],
  'amountPaid' : bigint,
  'invoiceNumber' : string,
  'notes' : [] | [string],
  'subtotal' : number,
}
export interface InvoiceLineItem {
  'rate' : number,
  'description' : string,
  'quantity' : number,
  'amount' : number,
}
export type InvoicePaymentStatus = { 'paid' : null } |
  { 'sent' : null } |
  { 'overdue' : null } |
  { 'draft' : null } |
  { 'viewed' : null } |
  { 'partial' : null };
export interface ListInternsFilter {
  'status' : [] | [Status],
  'space' : [] | [Space],
}
export interface Meeting {
  'id' : string,
  'title' : string,
  'joinLink' : [] | [string],
  'createdAt' : bigint,
  'createdBy' : string,
  'meetingType' : string,
  'durationMinutes' : bigint,
  'participantIds' : Array<string>,
  'reminderSentAt' : [] | [bigint],
  'scheduledAt' : bigint,
}
export interface MonthlyAnalyticsEntry {
  'month' : string,
  'approved' : bigint,
  'newLeads' : bigint,
  'rejected' : bigint,
}
export interface NoteComment {
  'id' : string,
  'status' : string,
  'content' : string,
  'authorId' : string,
  'createdAt' : bigint,
  'authorName' : string,
}
export interface Notification {
  'id' : string,
  'title' : string,
  'userId' : string,
  'notificationType' : NotificationType,
  'createdAt' : bigint,
  'isRead' : boolean,
  'message' : string,
  'priority' : [] | [NotificationPriority],
  'relatedId' : [] | [string],
}
export interface NotificationPreference {
  'userId' : string,
  'digestFrequency' : { 'hourly' : null } |
    { 'immediate' : null } |
    { 'daily' : null },
  'digestEnabled' : boolean,
  'eventType' : string,
}
export type NotificationPriority = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export type NotificationType = { 'taskAssigned' : null } |
  { 'proposalExpiring' : null } |
  { 'invoiceDue' : null } |
  { 'attendanceAnomaly' : null } |
  { 'announcementPosted' : null } |
  { 'dealSLABreached' : null } |
  { 'internDocumentSent' : null } |
  { 'taskOverdue' : null } |
  { 'announcement' : null } |
  { 'newClientAssigned' : null } |
  { 'invoiceOverdue' : null } |
  { 'leaveApproved' : null } |
  { 'approvalRequestCreated' : null } |
  { 'leaveRejected' : null } |
  { 'healthScoreLow' : null } |
  { 'followUpOverdue' : null } |
  { 'stageChanged' : null } |
  { 'proposalExpiringUrgent' : null } |
  { 'overdueFollowUp' : null } |
  { 'dealClosedWon' : null } |
  { 'staleDeal' : null };
export type PaymentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'overdue' : null };
export interface Performance {
  'id' : string,
  'month' : bigint,
  'overallScore' : number,
  'internId' : string,
  'createdAt' : bigint,
  'year' : bigint,
  'initiativeScore' : number,
  'attendanceScore' : number,
  'taskScore' : number,
  'communicationScore' : number,
  'adminNotes' : string,
}
export type PriorityLevel = { 'low' : null } |
  { 'high' : null } |
  { 'urgent' : null } |
  { 'medium' : null };
export interface ProjectMilestone {
  'id' : string,
  'status' : string,
  'completedAt' : [] | [bigint],
  'name' : string,
}
export interface ProjectParticipation {
  'id' : string,
  'status' : string,
  'projectName' : string,
  'internId' : string,
  'role' : string,
  'completionPercent' : bigint,
  'deliverables' : Array<string>,
  'startDate' : string,
  'milestones' : Array<ProjectMilestone>,
}
export interface RepScorecard {
  'totalDealValueClosed' : number,
  'username' : string,
  'displayName' : string,
  'userId' : string,
  'closedDealsCount' : bigint,
  'avgDealCycleTime' : number,
  'winRate' : number,
  'activityCount' : bigint,
}
export type Role = { 'hr' : null } |
  { 'manager' : null } |
  { 'admin' : null } |
  { 'finance' : null } |
  { 'marketing' : null } |
  { 'sales' : null } |
  { 'superAdmin' : null } |
  { 'operations' : null } |
  { 'viewer' : null };
export type SlaStatus = { 'notBreached' : null } |
  { 'breached' : null };
export type Space = { 'Org' : null } |
  { 'Learning' : null } |
  { 'Marketing' : null };
export type Status = { 'OnHold' : null } |
  { 'Active' : null } |
  { 'Completed' : null };
export interface StatusHistoryEntry {
  'status' : ClientStatus,
  'note' : string,
  'adminName' : string,
  'timestamp' : bigint,
}
export interface Task {
  'id' : string,
  'status' : string,
  'title' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'tags' : Array<string>,
  'description' : string,
  'deadline' : [] | [bigint],
  'updatedAt' : bigint,
  'assignedInternId' : string,
  'teamSpace' : string,
  'priority' : string,
}
export interface TimelineMilestone {
  'id' : string,
  'completedAt' : [] | [bigint],
  'title' : string,
  'internId' : string,
  'createdAt' : bigint,
  'description' : [] | [string],
  'milestoneType' : string,
}
export interface UpdateClientRequest {
  'source' : [] | [string],
  'serviceInterested' : [] | [string],
  'gstNumber' : [] | [string],
  'designation' : [] | [string],
  'tags' : [] | [Array<string>],
  'email' : [] | [string],
  'website' : [] | [string],
  'whatsappNumber' : [] | [string],
  'nextMeetingDate' : [] | [bigint],
  'companyName' : [] | [string],
  'leadSource' : [] | [string],
  'priorityLevel' : [] | [PriorityLevel],
  'dealValue' : [] | [number],
  'companySize' : [] | [string],
  'phone' : [] | [string],
  'industryType' : [] | [string],
  'contactPersonName' : [] | [string],
  'assignedTeamMember' : [] | [string],
  'location' : [] | [string],
  'followUpDate' : [] | [bigint],
}
export interface UpdateInternPayload {
  'status' : Status,
  'experienceLevel' : ExperienceLevel,
  'profilePicCid' : [] | [string],
  'name' : string,
  'joiningDate' : bigint,
  'email' : string,
  'space' : Space,
  'phone' : string,
  'department' : string,
  'adminNotes' : string,
}
export interface UpdatePerformancePayload {
  'month' : bigint,
  'overallScore' : number,
  'year' : bigint,
  'initiativeScore' : number,
  'attendanceScore' : number,
  'taskScore' : number,
  'communicationScore' : number,
  'adminNotes' : string,
}
export interface UpdateTaskPayload {
  'status' : [] | [string],
  'title' : [] | [string],
  'tags' : [] | [Array<string>],
  'description' : [] | [string],
  'deadline' : [] | [bigint],
  'assignedInternId' : [] | [string],
  'teamSpace' : [] | [string],
  'priority' : [] | [string],
}
export interface UserAccount {
  'id' : string,
  'username' : string,
  'displayName' : string,
  'createdAt' : bigint,
  'role' : Role,
  'isActive' : boolean,
  'passwordHash' : string,
  'spaces' : Array<string>,
}
export interface WorkSubmission {
  'id' : string,
  'status' : string,
  'title' : string,
  'githubLink' : [] | [string],
  'internId' : string,
  'createdAt' : bigint,
  'description' : string,
  'fileUrls' : Array<string>,
  'reviewedAt' : [] | [bigint],
  'reviewedBy' : [] | [string],
  'driveLink' : [] | [string],
  'taskId' : [] | [string],
  'adminFeedback' : [] | [string],
}
export interface WorkflowExecution {
  'id' : string,
  'ruleName' : string,
  'status' : { 'success' : null } |
    { 'failed' : null } |
    { 'running' : null },
  'errorMessage' : [] | [string],
  'recordsProcessed' : bigint,
  'triggeredAt' : bigint,
}
export interface WorkspaceData {
  'tasks' : Array<Task>,
  'meetings' : Array<Meeting>,
  'submissions' : Array<WorkSubmission>,
  'notes' : Array<DailyNote>,
  'channelMessages' : Array<ChannelMessage>,
  'directMessages' : Array<DirectMessage>,
  'milestones' : Array<TimelineMilestone>,
}
export interface _SERVICE {
  'addClientActivity' : ActorMethod<
    [string, ActivityType, string, [] | [string]],
    { 'ok' : ClientActivity } |
      { 'err' : string }
  >,
  'addClientComment' : ActorMethod<
    [string, string, [] | [string]],
    { 'ok' : ClientComment } |
      { 'err' : string }
  >,
  'addContact' : ActorMethod<
    [string, ContactPerson],
    { 'ok' : Client } |
      { 'err' : string }
  >,
  'addDocumentVersion' : ActorMethod<
    [string, string, string, string],
    { 'ok' : DocumentRecord } |
      { 'err' : string }
  >,
  'addNoteComment' : ActorMethod<
    [string, string, string, string],
    { 'ok' : DailyNote } |
      { 'err' : string }
  >,
  'addPerformance' : ActorMethod<
    [string, CreatePerformancePayload],
    { 'ok' : Performance } |
      { 'err' : string }
  >,
  'addProjectMilestone' : ActorMethod<
    [string, string, string, string],
    { 'ok' : ProjectParticipation } |
      { 'err' : string }
  >,
  'addTimelineMilestone' : ActorMethod<
    [string, string, string, [] | [string], string],
    { 'ok' : TimelineMilestone } |
      { 'err' : string }
  >,
  'approveRequest' : ActorMethod<
    [string, string, [] | [string]],
    { 'ok' : ApprovalRequest } |
      { 'err' : string }
  >,
  'archiveDocument' : ActorMethod<
    [string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'captureWonLostReason' : ActorMethod<
    [string, string],
    { 'ok' : Client } |
      { 'err' : string }
  >,
  'computeCompositeScore' : ActorMethod<
    [string, string],
    { 'ok' : CompositePerformanceScore } |
      { 'err' : string }
  >,
  'createAnnouncement' : ActorMethod<
    [{ 'title' : string, 'content' : string, 'createdBy' : string }],
    { 'ok' : Announcement } |
      { 'err' : string }
  >,
  'createAnnouncementV2' : ActorMethod<
    [string, string, string, Array<string>, [] | [bigint]],
    { 'ok' : Announcement } |
      { 'err' : string }
  >,
  'createApprovalRequest' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : ApprovalRequest } |
      { 'err' : string }
  >,
  'createChannel' : ActorMethod<
    [string, string, string, Array<string>],
    { 'ok' : Channel } |
      { 'err' : string }
  >,
  'createClient' : ActorMethod<
    [CreateClientRequest],
    { 'ok' : Client } |
      { 'err' : string }
  >,
  'createDailyNote' : ActorMethod<
    [string, CreateDailyNotePayload],
    { 'ok' : DailyNote } |
      { 'err' : string }
  >,
  'createDocumentRecord' : ActorMethod<
    [string, string, string, string, string, string, string],
    { 'ok' : DocumentRecord } |
      { 'err' : string }
  >,
  'createIntern' : ActorMethod<
    [string, CreateInternPayload],
    { 'ok' : Intern } |
      { 'err' : string }
  >,
  'createInternAudited' : ActorMethod<
    [string, CreateInternPayload],
    { 'ok' : Intern } |
      { 'err' : string }
  >,
  'createInvoice' : ActorMethod<
    [string, Array<InvoiceLineItem>, number, [] | [string]],
    { 'ok' : Invoice } |
      { 'err' : string }
  >,
  'createNotification' : ActorMethod<
    [
      {
        'title' : string,
        'userId' : string,
        'notificationType' : NotificationType,
        'message' : string,
        'priority' : NotificationPriority,
        'relatedId' : [] | [string],
      },
    ],
    { 'ok' : Notification } |
      { 'err' : string }
  >,
  'createProjectParticipation' : ActorMethod<
    [string, string, string, string, string, Array<string>],
    { 'ok' : ProjectParticipation } |
      { 'err' : string }
  >,
  'createSubmission' : ActorMethod<
    [string, CreateSubmissionPayload],
    { 'ok' : WorkSubmission } |
      { 'err' : string }
  >,
  'createTask' : ActorMethod<
    [string, CreateTaskPayload],
    { 'ok' : Task } |
      { 'err' : string }
  >,
  'createUser' : ActorMethod<
    [string, string, string, string, Array<string>, string],
    { 'ok' : UserAccount } |
      { 'err' : string }
  >,
  'deleteAnnouncement' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteAnnouncementById' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteClient' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'deleteClientComment' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteClientWithAudit' : ActorMethod<
    [string, string],
    { 'ok' : { 'deleted' : boolean, 'approvalId' : [] | [string] } } |
      { 'err' : string }
  >,
  'deleteDocument' : ActorMethod<
    [string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteIntern' : ActorMethod<
    [string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteInternWithAudit' : ActorMethod<
    [string, string],
    { 'ok' : { 'deleted' : boolean, 'approvalId' : [] | [string] } } |
      { 'err' : string }
  >,
  'deletePerformance' : ActorMethod<
    [string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteTask' : ActorMethod<
    [string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteUser' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getActivities' : ActorMethod<[[] | [string]], Array<Activity>>,
  'getAllTasks' : ActorMethod<[string], Array<Task>>,
  'getAnalyticsDashboard' : ActorMethod<[], AnalyticsData>,
  'getAnnouncementsBySpace' : ActorMethod<
    [string, [] | [string]],
    { 'ok' : Array<Announcement> } |
      { 'err' : string }
  >,
  'getAuditLog' : ActorMethod<
    [string, bigint, bigint],
    { 'ok' : Array<AuditEvent> } |
      { 'err' : string }
  >,
  'getCRMFunnelData' : ActorMethod<[], Array<[string, bigint]>>,
  'getChannelMessages' : ActorMethod<
    [string, string],
    { 'ok' : Array<ChannelMessage> } |
      { 'err' : string }
  >,
  'getChannelsForUser' : ActorMethod<[string], Array<Channel>>,
  'getClient' : ActorMethod<[string], { 'ok' : Client } | { 'err' : string }>,
  'getClientActivities' : ActorMethod<[string], Array<ClientActivity>>,
  'getClientAnalytics' : ActorMethod<[], ClientAnalytics>,
  'getClientComments' : ActorMethod<[string], Array<ClientComment>>,
  'getClientInvoices' : ActorMethod<[string], Array<Invoice>>,
  'getCompositeScore' : ActorMethod<[string], [] | [CompositePerformanceScore]>,
  'getDailyNotesByIntern' : ActorMethod<[string, string], Array<DailyNote>>,
  'getDashboardSnapshot' : ActorMethod<
    [string],
    { 'ok' : DashboardSnapshot } |
      { 'err' : string }
  >,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDealCycleTime' : ActorMethod<[], bigint>,
  'getDirectMessages' : ActorMethod<
    [string, string],
    { 'ok' : Array<DirectMessage> } |
      { 'err' : string }
  >,
  'getDocumentById' : ActorMethod<[string, string], [] | [DocumentRecord]>,
  'getDocumentVersionHistory' : ActorMethod<
    [string, string],
    { 'ok' : Array<DocumentVersion> } |
      { 'err' : string }
  >,
  'getDocumentsByIntern' : ActorMethod<[string, string], Array<DocumentRecord>>,
  'getFollowUpComplianceRate' : ActorMethod<
    [string],
    { 'ok' : Array<[string, number]> } |
      { 'err' : string }
  >,
  'getIntern' : ActorMethod<[string], [] | [Intern]>,
  'getLostDealAnalysis' : ActorMethod<[], Array<[string, bigint, bigint]>>,
  'getMeetingsForIntern' : ActorMethod<[string, string], Array<Meeting>>,
  'getMeetingsForUser' : ActorMethod<[string], Array<Meeting>>,
  'getNotificationPreferences' : ActorMethod<
    [string],
    { 'ok' : Array<NotificationPreference> } |
      { 'err' : string }
  >,
  'getNotificationsByPriority' : ActorMethod<
    [string, string],
    { 'ok' : Array<Notification> } |
      { 'err' : string }
  >,
  'getPipelineVelocity' : ActorMethod<
    [string],
    { 'ok' : Array<[string, number]> } |
      { 'err' : string }
  >,
  'getProjectsByIntern' : ActorMethod<
    [string, string],
    Array<ProjectParticipation>
  >,
  'getRepScorecards' : ActorMethod<
    [string],
    { 'ok' : Array<RepScorecard> } |
      { 'err' : string }
  >,
  'getSLABreachRatePerStage' : ActorMethod<
    [string],
    { 'ok' : Array<[string, number]> } |
      { 'err' : string }
  >,
  'getSLARules' : ActorMethod<[], Array<[string, bigint]>>,
  'getStageHistory' : ActorMethod<[string], Array<InternPipelineStageHistory>>,
  'getSubmissionsByIntern' : ActorMethod<
    [string, string],
    Array<WorkSubmission>
  >,
  'getTasksByIntern' : ActorMethod<[string, string], Array<Task>>,
  'getTasksBySpace' : ActorMethod<[string, string], Array<Task>>,
  'getTimelineForIntern' : ActorMethod<
    [string, string],
    Array<TimelineMilestone>
  >,
  'getUserById' : ActorMethod<
    [string, string],
    { 'ok' : UserAccount } |
      { 'err' : string }
  >,
  'getWinRateByMember' : ActorMethod<[], Array<[string, bigint, bigint]>>,
  'getWorkspaceData' : ActorMethod<
    [string, string],
    { 'ok' : WorkspaceData } |
      { 'err' : string }
  >,
  'initSampleData' : ActorMethod<[], bigint>,
  'listAnnouncements' : ActorMethod<[boolean], Array<Announcement>>,
  'listApprovalRequests' : ActorMethod<
    [string, [] | [string]],
    { 'ok' : Array<ApprovalRequest> } |
      { 'err' : string }
  >,
  'listClients' : ActorMethod<[], Array<Client>>,
  'listInterns' : ActorMethod<[ListInternsFilter], Array<Intern>>,
  'listNotifications' : ActorMethod<[string], Array<Notification>>,
  'listPerformances' : ActorMethod<[string], Array<Performance>>,
  'listUsers' : ActorMethod<
    [string],
    { 'ok' : Array<UserAccount> } |
      { 'err' : string }
  >,
  'listWorkflowExecutions' : ActorMethod<
    [[] | [string], bigint],
    Array<WorkflowExecution>
  >,
  'logQuickActivity' : ActorMethod<
    [string, string, string],
    { 'ok' : Client } |
      { 'err' : string }
  >,
  'logWhatsApp' : ActorMethod<
    [string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'login' : ActorMethod<
    [string, string],
    {
        'ok' : {
          'permissions' : Array<string>,
          'displayName' : string,
          'role' : string,
          'sessionToken' : string,
        }
      } |
      { 'err' : string }
  >,
  'logout' : ActorMethod<[string], undefined>,
  'markAllAsRead' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'markAsRead' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'markDirectMessageRead' : ActorMethod<
    [string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'pinClientComment' : ActorMethod<
    [string, boolean],
    { 'ok' : ClientComment } |
      { 'err' : string }
  >,
  'rejectRequest' : ActorMethod<
    [string, string, [] | [string]],
    { 'ok' : ApprovalRequest } |
      { 'err' : string }
  >,
  'removeContact' : ActorMethod<
    [string, string],
    { 'ok' : Client } |
      { 'err' : string }
  >,
  'runAllAutomationJobs' : ActorMethod<[], undefined>,
  'runAutomationJobs' : ActorMethod<[string], undefined>,
  'scheduleMeeting' : ActorMethod<
    [string, CreateMeetingPayload],
    { 'ok' : Meeting } |
      { 'err' : string }
  >,
  'seedSampleData' : ActorMethod<[], undefined>,
  'sendChannelMessage' : ActorMethod<
    [string, string, string, Array<string>],
    { 'ok' : ChannelMessage } |
      { 'err' : string }
  >,
  'sendDirectMessage' : ActorMethod<
    [string, string, string],
    { 'ok' : DirectMessage } |
      { 'err' : string }
  >,
  'setNotificationPreference' : ActorMethod<
    [string, string, boolean, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setSLARule' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateClient' : ActorMethod<
    [string, UpdateClientRequest],
    { 'ok' : Client } |
      { 'err' : string }
  >,
  'updateClientComment' : ActorMethod<
    [string, string],
    { 'ok' : ClientComment } |
      { 'err' : string }
  >,
  'updateClientStatus' : ActorMethod<
    [string, ClientStatus, string],
    { 'ok' : Client } |
      { 'err' : string }
  >,
  'updateContact' : ActorMethod<
    [string, string, ContactPerson],
    { 'ok' : Client } |
      { 'err' : string }
  >,
  'updateDocumentApproval' : ActorMethod<
    [string, string, string, string],
    { 'ok' : DocumentRecord } |
      { 'err' : string }
  >,
  'updateDocumentState' : ActorMethod<
    [string, string, string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'updateIntern' : ActorMethod<
    [string, string, UpdateInternPayload],
    { 'ok' : Intern } |
      { 'err' : string }
  >,
  'updateInternAudited' : ActorMethod<
    [string, string, UpdateInternPayload],
    { 'ok' : Intern } |
      { 'err' : string }
  >,
  'updateInternExtendedProfile' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [number],
      boolean,
      [] | [string],
      boolean,
    ],
    { 'ok' : Intern } |
      { 'err' : string }
  >,
  'updateInternPipelineStage' : ActorMethod<
    [string, string, InternPipelineStage, string],
    { 'ok' : Intern } |
      { 'err' : string }
  >,
  'updateInvoicePaymentStatus' : ActorMethod<
    [string, PaymentStatus],
    { 'ok' : Invoice } |
      { 'err' : string }
  >,
  'updateInvoiceStatus' : ActorMethod<
    [string, string, InvoicePaymentStatus, [] | [bigint]],
    { 'ok' : Invoice } |
      { 'err' : string }
  >,
  'updateMilestone' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : ProjectParticipation } |
      { 'err' : string }
  >,
  'updatePerformance' : ActorMethod<
    [string, string, UpdatePerformancePayload],
    { 'ok' : Performance } |
      { 'err' : string }
  >,
  'updateProjectParticipation' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      [] | [bigint],
      [] | [Array<string>],
    ],
    { 'ok' : ProjectParticipation } |
      { 'err' : string }
  >,
  'updateProposalStatus' : ActorMethod<
    [string, string, bigint],
    { 'ok' : Client } |
      { 'err' : string }
  >,
  'updateSubmissionStatus' : ActorMethod<
    [string, string, string, [] | [string]],
    { 'ok' : WorkSubmission } |
      { 'err' : string }
  >,
  'updateTask' : ActorMethod<
    [string, string, UpdateTaskPayload],
    { 'ok' : Task } |
      { 'err' : string }
  >,
  'updateUser' : ActorMethod<
    [string, string, string, Array<string>, boolean],
    { 'ok' : UserAccount } |
      { 'err' : string }
  >,
  'validateSession' : ActorMethod<
    [string],
    {
        'ok' : {
          'permissions' : Array<string>,
          'username' : string,
          'displayName' : string,
          'role' : string,
        }
      } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];