import typography from "@tailwindcss/typography";
import containerQueries from "@tailwindcss/container-queries";
import animate from "tailwindcss-animate";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["index.html", "src/**/*.{js,ts,jsx,tsx,html,css}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "oklch(var(--border))",
        input: "oklch(var(--input))",
        ring: "oklch(var(--ring) / <alpha-value>)",
        background: "oklch(var(--background))",
        foreground: "oklch(var(--foreground))",
        primary: {
          DEFAULT: "oklch(var(--primary) / <alpha-value>)",
          foreground: "oklch(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "oklch(var(--secondary) / <alpha-value>)",
          foreground: "oklch(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "oklch(var(--destructive) / <alpha-value>)",
          foreground: "oklch(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "oklch(var(--muted) / <alpha-value>)",
          foreground: "oklch(var(--muted-foreground) / <alpha-value>)",
        },
        accent: {
          DEFAULT: "oklch(var(--accent) / <alpha-value>)",
          foreground: "oklch(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "oklch(var(--popover))",
          foreground: "oklch(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "oklch(var(--card))",
          foreground: "oklch(var(--card-foreground))",
        },
        chart: {
          1: "oklch(var(--chart-1))",
          2: "oklch(var(--chart-2))",
          3: "oklch(var(--chart-3))",
          4: "oklch(var(--chart-4))",
          5: "oklch(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "oklch(var(--sidebar))",
          foreground: "oklch(var(--sidebar-foreground))",
          primary: "oklch(var(--sidebar-primary))",
          "primary-foreground": "oklch(var(--sidebar-primary-foreground))",
          accent: "oklch(var(--sidebar-accent))",
          "accent-foreground": "oklch(var(--sidebar-accent-foreground))",
          border: "oklch(var(--sidebar-border))",
          ring: "oklch(var(--sidebar-ring))",
        },
        "intern-applied": "oklch(var(--intern-applied))",
        "intern-screened": "oklch(var(--intern-screened))",
        "intern-interview-scheduled": "oklch(var(--intern-interview-scheduled))",
        "intern-interview-done": "oklch(var(--intern-interview-done))",
        "intern-decision-pending": "oklch(var(--intern-decision-pending))",
        "intern-offer-sent": "oklch(var(--intern-offer-sent))",
        "intern-offer-accepted": "oklch(var(--intern-offer-accepted))",
        "intern-offer-rejected": "oklch(var(--intern-offer-rejected))",
        "intern-onboarding": "oklch(var(--intern-onboarding))",
        "intern-active": "oklch(var(--intern-active))",
        "intern-performance-review": "oklch(var(--intern-performance-review))",
        "intern-completed": "oklch(var(--intern-completed))",
        "intern-alumni": "oklch(var(--intern-alumni))",
        "task-draft": "oklch(var(--task-draft))",
        "task-submitted": "oklch(var(--task-submitted))",
        "task-under-review": "oklch(var(--task-under-review))",
        "task-approved": "oklch(var(--task-approved))",
        "task-revision": "oklch(var(--task-revision))",
        "attendance-present": "oklch(var(--attendance-present))",
        "attendance-absent": "oklch(var(--attendance-absent))",
        "attendance-leave-request": "oklch(var(--attendance-leave-request))",
        "attendance-approved": "oklch(var(--attendance-approved))",
        "attendance-rejected": "oklch(var(--attendance-rejected))",
        "lms-not-started": "oklch(var(--lms-not-started))",
        "lms-in-progress": "oklch(var(--lms-in-progress))",
        "lms-completed": "oklch(var(--lms-completed))",
        "lms-certificate": "oklch(var(--lms-certificate))",
        "client-lead-captured": "oklch(var(--client-lead-captured))",
        "client-contacted": "oklch(var(--client-contacted))",
        "client-discovery-call": "oklch(var(--client-discovery-call))",
        "client-proposal-sent": "oklch(var(--client-proposal-sent))",
        "client-negotiation": "oklch(var(--client-negotiation))",
        "client-won": "oklch(var(--client-won))",
        "client-lost": "oklch(var(--client-lost))",
        "client-on-hold": "oklch(var(--client-on-hold))",
        "pipeline-need-to-talk": "oklch(var(--pipeline-need-to-talk))",
        "pipeline-just-talked": "oklch(var(--pipeline-just-talked))",
        "pipeline-in-progress": "oklch(var(--pipeline-in-progress))",
        "pipeline-approved": "oklch(var(--pipeline-approved))",
        "pipeline-rejected": "oklch(var(--pipeline-rejected))",
      },
      fontFamily: {
        display: ["var(--font-display)", "serif"],
        body: ["var(--font-body)", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgba(0,0,0,0.05)",
        "card-hover": '0 12px 24px 0 rgba(0,0,0,0.25)',
        elevated: '0 8px 16px 0 rgba(0,0,0,0.2)',
        pipeline: '0 4px 12px 0 rgba(0,0,0,0.15)',
        "chat-hover": '0 4px 12px 0 rgba(0,0,0,0.15)',
        "notes-card": '0 2px 8px 0 rgba(0,0,0,0.12)',
        "task-card": '0 2px 8px 0 rgba(0,0,0,0.12)',
        "timeline-node": '0 0 12px 0 rgba(231,21,20,0.1)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [typography, containerQueries, animate],
};
