/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateInternPayload {
    status: Status;
    experienceLevel: ExperienceLevel;
    profilePicCid?: string;
    name: string;
    joiningDate: bigint;
    email: string;
    space: Space;
    phone: string;
    department: string;
    adminNotes: string;
}
export interface Activity {
    id: string;
    action: string;
    internId: string;
    performedBy: string;
    timestamp: bigint;
    details: string;
}
export interface UpdateInternPayload {
    status: Status;
    experienceLevel: ExperienceLevel;
    profilePicCid?: string;
    name: string;
    joiningDate: bigint;
    email: string;
    space: Space;
    phone: string;
    department: string;
    adminNotes: string;
}
export interface Performance {
    id: string;
    month: bigint;
    overallScore: number;
    internId: string;
    createdAt: bigint;
    year: bigint;
    initiativeScore: number;
    attendanceScore: number;
    taskScore: number;
    communicationScore: number;
    adminNotes: string;
}
export interface CreatePerformancePayload {
    month: bigint;
    overallScore: number;
    internId: string;
    year: bigint;
    initiativeScore: number;
    attendanceScore: number;
    taskScore: number;
    communicationScore: number;
    adminNotes: string;
}
export interface UpdatePerformancePayload {
    month: bigint;
    overallScore: number;
    year: bigint;
    initiativeScore: number;
    attendanceScore: number;
    taskScore: number;
    communicationScore: number;
    adminNotes: string;
}
export interface Intern {
    id: string;
    status: Status;
    experienceLevel: ExperienceLevel;
    profilePicCid?: string;
    offerLetterSentAt?: bigint;
    name: string;
    createdAt: bigint;
    joiningDate: bigint;
    certificateOpened: boolean;
    completionLetterOpened: boolean;
    email: string;
    lastWhatsAppedAt?: bigint;
    certificateOpenedAt?: bigint;
    space: Space;
    updatedAt: bigint;
    offerLetterSent: boolean;
    certificateSentAt?: bigint;
    completionLetterSentAt?: bigint;
    completionLetterSent: boolean;
    offerLetterOpenedAt?: bigint;
    completionLetterOpenedAt?: bigint;
    phone: string;
    department: string;
    lastContactedAt?: bigint;
    adminNotes: string;
    offerLetterOpened: boolean;
    certificateSent: boolean;
}
export interface ListInternsFilter {
    status?: Status;
    space?: Space;
}
export interface DashboardStats {
    marketingCount: bigint;
    documentsSentThisMonth: bigint;
    orgCount: bigint;
    totalInterns: bigint;
    activeInterns: bigint;
    learningCount: bigint;
    avgPerformance: number;
}
export enum ExperienceLevel {
    Mid = "Mid",
    Junior = "Junior",
    Senior = "Senior"
}
export enum Space {
    Org = "Org",
    Learning = "Learning",
    Marketing = "Marketing"
}
export enum Status {
    OnHold = "OnHold",
    Active = "Active",
    Completed = "Completed"
}
export interface backendInterface {
    addPerformance(sessionToken: string, payload: CreatePerformancePayload): Promise<{
        __kind__: "ok";
        ok: Performance;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createIntern(sessionToken: string, payload: CreateInternPayload): Promise<{
        __kind__: "ok";
        ok: Intern;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteIntern(sessionToken: string, id: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deletePerformance(sessionToken: string, id: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getActivities(internId: string | null): Promise<Array<Activity>>;
    getDashboardStats(): Promise<DashboardStats>;
    getIntern(id: string): Promise<Intern | null>;
    initSampleData(): Promise<bigint>;
    listInterns(filter: ListInternsFilter): Promise<Array<Intern>>;
    listPerformances(internId: string): Promise<Array<Performance>>;
    logWhatsApp(sessionToken: string, internId: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    login(username: string, password: string): Promise<{
        __kind__: "ok";
        ok: {
            displayName: string;
            sessionToken: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    logout(sessionToken: string): Promise<void>;
    seedSampleData(): Promise<void>;
    updateDocumentState(sessionToken: string, internId: string, docType: string, action: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateIntern(sessionToken: string, id: string, payload: UpdateInternPayload): Promise<{
        __kind__: "ok";
        ok: Intern;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updatePerformance(sessionToken: string, id: string, payload: UpdatePerformancePayload): Promise<{
        __kind__: "ok";
        ok: Performance;
    } | {
        __kind__: "err";
        err: string;
    }>;
    validateSession(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: {
            username: string;
            displayName: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { CreateInternPayload as _CreateInternPayload, ExperienceLevel as _ExperienceLevel, Intern as _Intern, ListInternsFilter as _ListInternsFilter, Performance as _Performance, Space as _Space, Status as _Status, UpdateInternPayload as _UpdateInternPayload } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addPerformance(arg0: string, arg1: CreatePerformancePayload): Promise<{
        __kind__: "ok";
        ok: Performance;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addPerformance(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPerformance(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createIntern(arg0: string, arg1: CreateInternPayload): Promise<{
        __kind__: "ok";
        ok: Intern;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createIntern(arg0, to_candid_CreateInternPayload_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIntern(arg0, to_candid_CreateInternPayload_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteIntern(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIntern(arg0, arg1);
                return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIntern(arg0, arg1);
            return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePerformance(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePerformance(arg0, arg1);
                return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePerformance(arg0, arg1);
            return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivities(arg0: string | null): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivities(to_candid_opt_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivities(to_candid_opt_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getIntern(arg0: string): Promise<Intern | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIntern(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIntern(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async initSampleData(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.initSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSampleData();
            return result;
        }
    }
    async listInterns(arg0: ListInternsFilter): Promise<Array<Intern>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInterns(to_candid_ListInternsFilter_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInterns(to_candid_ListInternsFilter_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPerformances(arg0: string): Promise<Array<Performance>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPerformances(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPerformances(arg0);
            return result;
        }
    }
    async logWhatsApp(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.logWhatsApp(arg0, arg1);
                return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWhatsApp(arg0, arg1);
            return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: {
            displayName: string;
            sessionToken: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async seedSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleData();
            return result;
        }
    }
    async updateDocumentState(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDocumentState(arg0, arg1, arg2, arg3);
                return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDocumentState(arg0, arg1, arg2, arg3);
            return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateIntern(arg0: string, arg1: string, arg2: UpdateInternPayload): Promise<{
        __kind__: "ok";
        ok: Intern;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIntern(arg0, arg1, to_candid_UpdateInternPayload_n28(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIntern(arg0, arg1, to_candid_UpdateInternPayload_n28(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePerformance(arg0: string, arg1: string, arg2: UpdatePerformancePayload): Promise<{
        __kind__: "ok";
        ok: Performance;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePerformance(arg0, arg1, arg2);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePerformance(arg0, arg1, arg2);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateSession(arg0: string): Promise<{
        __kind__: "ok";
        ok: {
            username: string;
            displayName: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSession(arg0);
                return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSession(arg0);
            return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ExperienceLevel_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExperienceLevel): ExperienceLevel {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Intern_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Intern): Intern {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Space_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Space): Space {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Intern]): Intern | null {
    return value.length === 0 ? null : from_candid_Intern_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status;
    experienceLevel: _ExperienceLevel;
    profilePicCid: [] | [string];
    offerLetterSentAt: [] | [bigint];
    name: string;
    createdAt: bigint;
    joiningDate: bigint;
    certificateOpened: boolean;
    completionLetterOpened: boolean;
    email: string;
    lastWhatsAppedAt: [] | [bigint];
    certificateOpenedAt: [] | [bigint];
    space: _Space;
    updatedAt: bigint;
    offerLetterSent: boolean;
    certificateSentAt: [] | [bigint];
    completionLetterSentAt: [] | [bigint];
    completionLetterSent: boolean;
    offerLetterOpenedAt: [] | [bigint];
    completionLetterOpenedAt: [] | [bigint];
    phone: string;
    department: string;
    lastContactedAt: [] | [bigint];
    adminNotes: string;
    offerLetterOpened: boolean;
    certificateSent: boolean;
}): {
    id: string;
    status: Status;
    experienceLevel: ExperienceLevel;
    profilePicCid?: string;
    offerLetterSentAt?: bigint;
    name: string;
    createdAt: bigint;
    joiningDate: bigint;
    certificateOpened: boolean;
    completionLetterOpened: boolean;
    email: string;
    lastWhatsAppedAt?: bigint;
    certificateOpenedAt?: bigint;
    space: Space;
    updatedAt: bigint;
    offerLetterSent: boolean;
    certificateSentAt?: bigint;
    completionLetterSentAt?: bigint;
    completionLetterSent: boolean;
    offerLetterOpenedAt?: bigint;
    completionLetterOpenedAt?: bigint;
    phone: string;
    department: string;
    lastContactedAt?: bigint;
    adminNotes: string;
    offerLetterOpened: boolean;
    certificateSent: boolean;
} {
    return {
        id: value.id,
        status: from_candid_Status_n13(_uploadFile, _downloadFile, value.status),
        experienceLevel: from_candid_ExperienceLevel_n15(_uploadFile, _downloadFile, value.experienceLevel),
        profilePicCid: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.profilePicCid)),
        offerLetterSentAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.offerLetterSentAt)),
        name: value.name,
        createdAt: value.createdAt,
        joiningDate: value.joiningDate,
        certificateOpened: value.certificateOpened,
        completionLetterOpened: value.completionLetterOpened,
        email: value.email,
        lastWhatsAppedAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.lastWhatsAppedAt)),
        certificateOpenedAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.certificateOpenedAt)),
        space: from_candid_Space_n19(_uploadFile, _downloadFile, value.space),
        updatedAt: value.updatedAt,
        offerLetterSent: value.offerLetterSent,
        certificateSentAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.certificateSentAt)),
        completionLetterSentAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.completionLetterSentAt)),
        completionLetterSent: value.completionLetterSent,
        offerLetterOpenedAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.offerLetterOpenedAt)),
        completionLetterOpenedAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.completionLetterOpenedAt)),
        phone: value.phone,
        department: value.department,
        lastContactedAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.lastContactedAt)),
        adminNotes: value.adminNotes,
        offerLetterOpened: value.offerLetterOpened,
        certificateSent: value.certificateSent
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Performance;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Performance;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Intern;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Intern;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Intern_n11(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    OnHold: null;
} | {
    Active: null;
} | {
    Completed: null;
}): Status {
    return "OnHold" in value ? Status.OnHold : "Active" in value ? Status.Active : "Completed" in value ? Status.Completed : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Mid: null;
} | {
    Junior: null;
} | {
    Senior: null;
}): ExperienceLevel {
    return "Mid" in value ? ExperienceLevel.Mid : "Junior" in value ? ExperienceLevel.Junior : "Senior" in value ? ExperienceLevel.Senior : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Org: null;
} | {
    Learning: null;
} | {
    Marketing: null;
}): Space {
    return "Org" in value ? Space.Org : "Learning" in value ? Space.Learning : "Marketing" in value ? Space.Marketing : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        displayName: string;
        sessionToken: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        displayName: string;
        sessionToken: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        username: string;
        displayName: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        username: string;
        displayName: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Intern>): Array<Intern> {
    return value.map((x)=>from_candid_Intern_n11(_uploadFile, _downloadFile, x));
}
function to_candid_CreateInternPayload_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateInternPayload): _CreateInternPayload {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_ExperienceLevel_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceLevel): _ExperienceLevel {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_ListInternsFilter_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListInternsFilter): _ListInternsFilter {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_Space_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Space): _Space {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateInternPayload_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateInternPayload): _UpdateInternPayload {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: Status;
    space?: Space;
}): {
    status: [] | [_Status];
    space: [] | [_Space];
} {
    return {
        status: value.status ? candid_some(to_candid_Status_n4(_uploadFile, _downloadFile, value.status)) : candid_none(),
        space: value.space ? candid_some(to_candid_Space_n8(_uploadFile, _downloadFile, value.space)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Status;
    experienceLevel: ExperienceLevel;
    profilePicCid?: string;
    name: string;
    joiningDate: bigint;
    email: string;
    space: Space;
    phone: string;
    department: string;
    adminNotes: string;
}): {
    status: _Status;
    experienceLevel: _ExperienceLevel;
    profilePicCid: [] | [string];
    name: string;
    joiningDate: bigint;
    email: string;
    space: _Space;
    phone: string;
    department: string;
    adminNotes: string;
} {
    return {
        status: to_candid_Status_n4(_uploadFile, _downloadFile, value.status),
        experienceLevel: to_candid_ExperienceLevel_n6(_uploadFile, _downloadFile, value.experienceLevel),
        profilePicCid: value.profilePicCid ? candid_some(value.profilePicCid) : candid_none(),
        name: value.name,
        joiningDate: value.joiningDate,
        email: value.email,
        space: to_candid_Space_n8(_uploadFile, _downloadFile, value.space),
        phone: value.phone,
        department: value.department,
        adminNotes: value.adminNotes
    };
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    OnHold: null;
} | {
    Active: null;
} | {
    Completed: null;
} {
    return value == Status.OnHold ? {
        OnHold: null
    } : value == Status.Active ? {
        Active: null
    } : value == Status.Completed ? {
        Completed: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceLevel): {
    Mid: null;
} | {
    Junior: null;
} | {
    Senior: null;
} {
    return value == ExperienceLevel.Mid ? {
        Mid: null
    } : value == ExperienceLevel.Junior ? {
        Junior: null
    } : value == ExperienceLevel.Senior ? {
        Senior: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Space): {
    Org: null;
} | {
    Learning: null;
} | {
    Marketing: null;
} {
    return value == Space.Org ? {
        Org: null
    } : value == Space.Learning ? {
        Learning: null
    } : value == Space.Marketing ? {
        Marketing: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
